### ISSUE TITLE
Add CORS support

### ISSUE THREAD

**Issue by sietseringers** [bwesterb/atumd#1]
In IRMA we use `atumd` as timestamp server for [attribute-based signatures](https://irma.app/docs/overview/#attribute-based-signatures). In particular, during verification of such signatures the `/checkPublicKey` endpoint is invoked. In one of the projects currently being done at the Privacy by Design Foundation, [`irmago`](https://github.com/privacybydesign/irmago) whicn depends on `atum` has been cross-compiled to WebAssembly and made into a browser plugin. Since this request now originates from a browser, we need the server to return CORS headers.

Do you think it would be appropriate to add support for that to `atumd`? If we were to add that, would you be willing to merge it? If so, to which endpoints do you think we should add support for this? Just the `/checkPublicKey`, or to others as well?

**Comment by bwesterb** [comment]
Makes perfect sense for all requests. Happy to merge.
